<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_robot">

  <!-- Robot Base Parameters -->
  <xacro:property name="base_radius" value="0.2"/>
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="arm_length" value="0.3"/>
  <xacro:property name="platform_radius" value="0.1"/>
  <xacro:property name="platform_height" value="0.02"/>
  
  <!-- Include Gazebo ROS control plugin -->
  <xacro:include filename="$(find cell_description)/urdf/delta_robot.gazebo.xacro"/>
  <xacro:include filename="$(find cell_description)/urdf/delta_robot.transmission.xacro"/>
  
  <!-- Robot Base Link -->
  <link name="world"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 1.0" rpy="0 0 0"/>
  </joint>
  
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>
  
  <!-- Arm 1 -->
  <joint name="arm1_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm1"/>
    <origin xyz="${base_radius-0.05} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="2"/>
  </joint>
  
  <link name="arm1">
    <visual>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Arm 2 -->
  <joint name="arm2_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm2"/>
    <origin xyz="-${base_radius/2} ${base_radius*0.866} 0" rpy="0 0 2.0944"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="2"/>
  </joint>
  
  <link name="arm2">
    <visual>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Arm 3 -->
  <joint name="arm3_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm3"/>
    <origin xyz="-${base_radius/2} -${base_radius*0.866} 0" rpy="0 0 -2.0944"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="2"/>
  </joint>
  
  <link name="arm3">
    <visual>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_length} 0.02 0.02"/>
      </geometry>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- End effector platform -->
  <joint name="platform_joint" type="fixed">
    <parent link="arm1"/>
    <child link="platform"/>
    <origin xyz="${arm_length} 0 -0.2" rpy="0 0 0"/>
  </joint>
  
  <link name="platform">
    <visual>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_height}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Tool Center Point -->
  <joint name="tool_joint" type="fixed">
    <parent link="platform"/>
    <child link="tool_link"/>
    <origin xyz="0 0 -0.02" rpy="0 0 0"/>
  </joint>
  
  <link name="tool_link">
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- End-effector frame (for MoveIt) -->
  <link name="ee_link"/>
  
  <joint name="ee_joint" type="fixed">
    <parent link="tool_link"/>
    <child link="ee_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
