name: CI

"on":
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: humble
      - name: Install dependencies
        run: |
          sudo apt-get update
      - name: Install ROS packages
        run: |
          sudo apt-get install -y \
            build-essential \
            ros-humble-desktop \
            ros-humble-moveit \
            ros-humble-gazebo-ros-pkgs \
            ros-humble-gazebo-ros2-control \
            ros-humble-ros2-control \
            ros-humble-ros2-controllers \
            ros-humble-realsense2-camera \
            ros-humble-realsense2-description \
            ros-humble-vision-msgs \
            ros-humble-tf2-ros \
            ros-humble-tf2-geometry-msgs \
            ros-humble-xacro \
            ros-humble-joint-state-publisher \
            ros-humble-joint-state-publisher-gui \
            ros-humble-robot-state-publisher \
            ros-humble-rviz2
      - name: Install ROS dependencies with rosdep
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --rosdistro humble -y --ignore-src
      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_cohesion+
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/**/test_results/**/*.xml
