name: CI

"on":
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: ros-tooling/setup-ros@cf741628ddbaf279f8cca1b208312bf25ae0e4b4
        with:
          required-ros-distributions: humble
      - name: Install dependencies
        run: sudo apt-get update
      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_cohesion+
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5
        with:
          name: test-results
          path: build/**/test_results/**/*.xml
