name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --rosdistro humble -y --ignore-src
          sudo apt-get update
          sudo apt-get install -y ros-humble-ament-lint-auto

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Test
        run: |
          source install/setup.bash
          colcon test
